version: "3"
services:
  client-app:
    image: chaptertran97/authentication-client
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: chaptertran97/authentication-server
    ports:
      - "8000:8000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: social
      MONGO_INITDB_ROOT_PASSWORD: OnwT42KAaWIOEYge
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local